version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${CUBEJS_DB_USER}
      POSTGRES_PASSWORD: ${CUBEJS_DB_PASS}
      POSTGRES_DB: ${CUBEJS_DB_NAME}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - cube-network
    restart: unless-stopped

  cube-app:
    build: .
    command: npm run dev
    environment:
      CUBEJS_DB_HOST: ${CUBEJS_DB_HOST}
      CUBEJS_DB_NAME: ${CUBEJS_DB_NAME}
      CUBEJS_DB_USER: ${CUBEJS_DB_USER}
      CUBEJS_DB_PASS: ${CUBEJS_DB_PASS}
    ports:
      - "4000:4000"
    networks:
      - cube-network
    restart: always
    depends_on:
      - postgres

networks:
  cube-network:
volumes:
  postgres: